[workspace]
members = [
    "src/merg",
    "src/merg_derive",
]
resolver = "2"

[workspace.dependencies]
merg = { path = "src/merg", version = "0.1" }
merg_derive = { path = "src/merg_derive", version = "0.1" }
